import LegalPageLayout from "@/components/LegalPageLayout";

const MultilingualRights = () => {
  const sections = [
    { id: "intro", title: "Introduction" },
    { id: "multilingual-works", title: "1. Multilingual Works" },
    { id: "ownership", title: "2. Ownership & Rights" },
    { id: "international-transfers", title: "3. International Data Transfers" },
    { id: "quality-standards", title: "4. Quality & Cultural Standards" },
  ];

  return (
    <LegalPageLayout
      title="Multilingual and International Rights Addendum"
      lastUpdated="October 2025"
      sections={sections}
    >
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebPage",
          "name": "Multilingual and International Rights - FutureCandy",
          "description": "Multilingual and International Rights Addendum for FutureCandy, detailing our approach to global music distribution and language versions.",
          "publisher": {
            "@type": "Organization",
            "name": "FutureCandy",
            "url": "https://futurecandy.online"
          }
        })}
      </script>

      <div className="prose prose-invert max-w-none space-y-8">
        <div id="intro" className="glass p-8 rounded-lg scroll-mt-24">
          <p className="text-lg mb-4 text-candy-cyan">
            This addendum outlines FutureCandy's policies regarding multilingual productions, international distribution, 
            and the creation of language-specific master recordings using AI-assisted translation and adaptation systems.
          </p>
          <p className="mb-4">
            All multilingual works are created to the same artistic and technical standards as our English-language productions, 
            with full respect for cultural context and linguistic nuance.
          </p>
          <p>
            For complete context, please review this addendum alongside our{" "}
            <a href="/terms" className="text-candy-cyan hover:underline">Terms of Use</a>,{" "}
            <a href="/digital-licensing" className="text-candy-cyan hover:underline">Licensing Policy</a>, and{" "}
            <a href="/privacy" className="text-candy-cyan hover:underline">Privacy Policy</a>.
          </p>
        </div>

        <section id="multilingual-works" className="glass p-8 rounded-lg scroll-mt-24">
          <h2 className="text-2xl font-bold text-candy-cyan mb-4">1. Multilingual Works</h2>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">1.1. Nature of Language Versions</h3>
          <p className="mb-4">
            FutureCandy may create, reproduce, and distribute alternative-language versions of any musical work using 
            AI voice synthesis and lyric translation models. Each language version constitutes a distinct master recording 
            while sharing the same underlying composition rights.
          </p>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">1.2. Independent Master Recordings</h3>
          <p className="mb-4">
            Each translation or language adaptation generated by FutureCandy is a separate master recording with:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>Unique ISRC (International Standard Recording Code)</li>
            <li>Dedicated metadata and rights registration</li>
            <li>Independent distribution and royalty tracking</li>
            <li>Language-specific artwork and promotional materials where appropriate</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">1.3. Supported Languages</h3>
          <p>
            FutureCandy produces multilingual versions in various languages including but not limited to: 
            English, Spanish (Español), Japanese (日本語), French (Français), German (Deutsch), Korean (한국어), 
            Mandarin Chinese (中文), Portuguese (Português), and others as demand and artistic vision require.
          </p>
        </section>

        <section id="ownership" className="glass p-8 rounded-lg scroll-mt-24">
          <h2 className="text-2xl font-bold text-candy-violet mb-4">2. Ownership & Rights Management</h2>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">2.1. Exclusive Ownership</h3>
          <p className="mb-4">
            FutureCandy retains 100% ownership of all multilingual masters and associated intellectual property, including:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>Master recording rights in all languages</li>
            <li>Translated lyrics and adapted compositions</li>
            <li>Metadata, track titles, and promotional text</li>
            <li>Artwork and visual assets</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">2.2. Licensee Restrictions</h3>
          <p className="mb-4">
            Third parties who license FutureCandy music may not:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>Create or commission their own language versions</li>
            <li>Alter existing multilingual masters</li>
            <li>Translate or adapt lyrics without prior written consent</li>
            <li>Sub-license language-specific versions to other territories</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">2.3. Regional Licensing</h3>
          <p>
            Licensees seeking language-specific versions for particular markets should submit requests through our{" "}
            <a href="/global-licensing" className="text-candy-cyan hover:underline">Global Licensing</a> form. 
            Each request will be evaluated based on artistic merit, cultural appropriateness, and commercial viability.
          </p>
        </section>

        <section id="international-transfers" className="glass p-8 rounded-lg scroll-mt-24">
          <h2 className="text-2xl font-bold text-candy-pink mb-4">3. International Data Transfers</h2>
          
          <h3 className="text-xl font-semibold text-candy-cyan mt-6 mb-3">3.1. Data Processing for Global Distribution</h3>
          <p className="mb-4">
            For global distribution and royalty management, FutureCandy shares limited metadata with international 
            streaming platforms, collection societies, and licensing partners. This may include:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>Track titles and artist identifiers</li>
            <li>ISRC and rights ownership information</li>
            <li>Territory-specific release dates</li>
            <li>Language and market categorization</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-cyan mt-6 mb-3">3.2. GDPR Compliance</h3>
          <p className="mb-4">
            All international data transfers comply with UK GDPR and applicable adequacy frameworks, including:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>UK-US Data Bridge for transfers to United States</li>
            <li>EU Standard Contractual Clauses where relevant</li>
            <li>Partner compliance verification for third-party processors</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-cyan mt-6 mb-3">3.3. User Rights</h3>
          <p>
            For information on how we handle personal data in international contexts, please refer to our{" "}
            <a href="/privacy" className="text-candy-cyan hover:underline">Privacy Policy</a>.
          </p>
        </section>

        <section id="quality-standards" className="glass p-8 rounded-lg scroll-mt-24">
          <h2 className="text-2xl font-bold text-candy-violet mb-4">4. Quality & Cultural Standards</h2>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">4.1. Translation Process</h3>
          <p className="mb-4">
            All multilingual versions undergo a rigorous quality control process:
          </p>
          <ol className="space-y-2 list-decimal list-inside mb-4">
            <li>Initial translation using AI language models</li>
            <li>Human review for cultural sensitivity and artistic alignment</li>
            <li>Vocal synthesis and production refinement</li>
            <li>Final approval by FutureCandy creative directors</li>
          </ol>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">4.2. Cultural Respect</h3>
          <p className="mb-4">
            FutureCandy is committed to producing culturally respectful adaptations. Our review process includes:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>Verification of idiomatic accuracy</li>
            <li>Assessment of cultural references and sensitivities</li>
            <li>Consultation with native speakers where appropriate</li>
            <li>Avoidance of direct translation in favor of emotional equivalence</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">4.3. Artistic Adaptations</h3>
          <p className="mb-4">
            Translation and localization features are generated using supervised AI systems. Artistic adaptations may 
            differ from literal linguistic equivalents to preserve:
          </p>
          <ul className="space-y-2 list-disc list-inside mb-4">
            <li>Melodic phrasing and vocal flow</li>
            <li>Emotional tone and narrative intent</li>
            <li>Cultural resonance with target audiences</li>
            <li>Brand consistency across all FutureCandy releases</li>
          </ul>
          
          <h3 className="text-xl font-semibold text-candy-pink mt-6 mb-3">4.4. Technical Standards</h3>
          <p>
            All multilingual masters meet the same technical specifications as our English productions, including 
            high-fidelity audio encoding, mastering for streaming platforms, and metadata accuracy for international 
            distribution systems.
          </p>
        </section>

        <div className="glass p-8 rounded-lg">
          <h3 className="text-xl font-bold text-candy-cyan mb-4">Contact Information</h3>
          <p className="mb-4">
            For inquiries regarding multilingual licensing, regional versions, or international rights:
          </p>
          <p className="mb-2">
            <strong>Email:</strong>{" "}
            <a href="mailto:licensing@futurecandy.online" className="text-candy-cyan hover:underline">
              licensing@futurecandy.online
            </a>
          </p>
          <p className="mb-4">
            <strong>Global Licensing Form:</strong>{" "}
            <a href="/global-licensing" className="text-candy-cyan hover:underline">
              Submit a Request
            </a>
          </p>
          <p className="text-sm text-muted-foreground">
            FutureCandy — A subsidiary of HEALTH CHOICES GLOBAL LIMITED<br />
            Company No. 10941962 | 128 City Road, London, United Kingdom, EC1V 2NX
          </p>
        </div>
      </div>
    </LegalPageLayout>
  );
};

export default MultilingualRights;
